Split travis tests out to individual jobs; should reduce some redundancy and maybe overall build time

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -14,10 +14,12 @@ cache:
     - $HOME/.ansible/roles
 
 env:
-  - ANSIBLE_VERSION="2.1"
-  - ANSIBLE_VERSION="2.2"
-  - ANSIBLE_VERSION="2.3"
-  - ANSIBLE_VERSION="2.4"
+  - ANSIBLE_VERSION="2.4" TEST_SUITE=idempotence
+  - ANSIBLE_VERSION="2.5" TEST_SUITE=idempotence
+  - ANSIBLE_VERSION="2.4" TEST_SUITE=trusty
+  - ANSIBLE_VERSION="2.5" TEST_SUITE=trusty
+  - ANSIBLE_VERSION="2.4" TEST_SUITE=xenial
+  - ANSIBLE_VERSION="2.5" TEST_SUITE=xenial
 
 before_install:
   - sudo apt-get update -qq
@@ -40,19 +42,21 @@ install:
 
 script:
   # Syntax check
-  - ansible-playbook travis-playbook.yml --syntax-check
+  - if [ $TEST_SUITE = "idempotence" ]; then ansible-playbook travis-playbook.yml --syntax-check; fi
 
   # Play test
-  - rake ansible:playbook[travis-playbook.yml]
+  - if [ $TEST_SUITE = "idempotence" ]; then rake ansible:playbook[travis-playbook.yml]; fi
 
   # Idempotence test
-  - rake ansible:playbook[travis-playbook.yml] > idempotence.out
+  - if [ $TEST_SUITE = "idempotence" ]; then rake ansible:playbook[travis-playbook.yml] > idempotence.out; fi
   - >
+    if [ $TEST_SUITE = "idempotence" ]; then
     grep -q "changed=0.*failed=0" idempotence.out
-    && (echo "Idempotence test: pass" && exit 0) || (echo "Idempotence test: fail" && cat idempotence.out && exit 1)
+    && (echo "Idempotence test: pass" && exit 0) || (echo "Idempotence test: fail" && cat idempotence.out && exit 1);
+    fi
 
   # Serverspec
-  - rake spec
+  - if [ $TEST_SUITE != "idempotence" ]; then rake spec:$TEST_SUITE; fi
 
 after_script:
   - rake environment:destroy
